### ISSUE TITLE
Implement Wishlist Functionality

### ISSUE THREAD

**Issue by chancandan** [chancandan/the_cheese_shoppe#4]
Develop a Wishlist feature that allows users to save products they are interested in for future purchases. This feature should allow users to add and remove items from their wishlist and ensure the data is stored appropriately.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added Wishlist functionality to allow users to save products they are interested in for future purchases. This includes adding and removing items from the wishlist, and ensuring the data is stored appropriately.

You can review changes in this commit: https://github.com/mnmnk43434/chancandan-the_cheese_shoppe-4/commit/d475f0c75ff90706dec5ae51390a2791619f14be.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
